# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psJUS9ZffAamWFoXYb9A5sxHKr6sj6DR
"""

name = "Arooba"
print(len(name))

from re import MULTILINE
name = "Arooba"
message = "Hello world"
MULTILINE = "this is a multiline"

name = "Arooba"
print(name[0:2])

paragraph = "Web development is the process of creating, building, and maintaining websites and web applications that run online, ranging from simple static pages to complex, interactive platforms"
print(paragraph.find("applications"))

paragraph = "Front-end: Responsible for the look, feel, and user interaction."
print(paragraph)

nmae = "Arooba"
print(name)

name = "Arooba"
input = "enter a name"
print(input)

text = "I love python"
new_text = text.replace("python" ,"java")
print(new_text)

text = "Hello World"
print(text.strip)
print(text.lstrip)
print(text.rstrip)